### ISSUE TITLE
Current sample/EGAF lookup table is incomplete causing previously valid projects to fail

### ISSUE THREAD

**Issue by hknahal** [icgc-dcc/dcc-submission#69]
The current sample/EGAF lookup table (actually a view called "ega_sample_mapping") appears incomplete and is causing previously valid data submissions to fail. It appears the current table is truncated. 

NOTE: As of 12:00 Sept 14, the “view_ega_sample_mapping" table is pointing to the most recent lookup table --> “ega_sample_mapping_1536930113”

Current lookup database (from Friday Sept 14 at 1:00PM GMT) contains only 31,492 rows.
 
```
icgc_metadata=> SELECT COUNT(*) FROM ega.view_ega_sample_mapping;
 count
-------
 31492
(1 row)
```
 
Previous version of database (from Friday Sept 14 at 1:00am GMT) contains 327,954 rows:
 
```
icgc_metadata=> SELECT COUNT(*) FROM ega.ega_sample_mapping_1536887100;
 count
--------
 327954
(1 row)
```

The current table (view_ega_sample_mapping) contains only half of the expected number of EGA datasets (163 vs 373). It's unclear why (the "bad_ega_sample_metadata" table is empty so it doesn't appear to be an EGA dataset issue), but perhaps the metadata at EGA was being re-freshed at the same time, and only half of the EGA datasets were captured. In any case, the cron job will need to be run again manually to re-generate the database, so we can check to see if all the EGA datasets are captured.

**Comment by andricDu** [comment]
@hknahal have you tried since? Are you sure this wasn't related to the scheduled IT outage?

I just ran a count query and got back 327,954 results.

**Comment by hknahal** [comment]
Thanks @andricDu It seems to be back to normal now. It contains the complete number of datasets (373) now. As you mentioned, it was most likely due to the IT outage.
