### ISSUE TITLE
Create an endpoint for icgcdcc admin to refresh sample/EGAF lookup table

### ISSUE THREAD

**Issue by hknahal** [icgc-dcc/dcc-submission#70]
Currently a cron job re-generates a sample-to-EGA File ID lookup table twice a day (9:00AM and 9:00PM EST). However, due to the high data submission activity at EGA during a Release, it is necessary to re-generate the database more frequently to fetch the latest metadata from EGA so a project can validate their DCC submission. In the past, I would ask Grant to do this when necessary, but ideally it would be good to have an endpoint (perhaps restricted to just the icgdcc admin account) that would allow me to do this independently. This endpoint could just be a curl command (similar to the way we can update a dictionary - see [here](https://wiki.oicr.on.ca/display/DCCSOFT/Admin+SOP#AdminSOP-Updatedictionary)), or a way to run the cron job.

**Comment by alekspejovic** [comment]
Confirmed with @hknahal , done with submission system, so closing.
