### ISSUE TITLE
EGA File Validation failing

### ISSUE THREAD

**Issue by hknahal** [icgc-dcc/dcc-submission#72]
The `ega.view_ega_sample_mapping` table (the sample/EGAF lookup table) is currently empty and causing all new data submissions to fail validation. 

```
icgc_metadata=> SELECT COUNT(*) FROM ega.view_ega_sample_mapping;
 count
-------
     0
(1 row)
```

**Comment by andricDu** [comment]
I believe this was fixed when IT restarted the services.
